project:
  type: website
  output-dir: docs
  resources: [evaluace.xlsx, .nojekyll]

website:
  title: "esif-evaluace"
  # page-footer: Kód
  search: false
  navbar: false

format:
  html:
    theme: cosmo
    css: style.css
    toc: false
    link-external-newwindow: true


execute:
  echo: false
  message: false
  warning: false

lang: cs
language:
  title-block-published: "Aktualizováno"




